### ISSUE TITLE
Cannot add nullable TIMESTAMP column

### ISSUE THREAD

**Issue by CYBAI** [k0kubun/sqldef#63] opened 2020-09-24 03:07 UTC
## Problem

With adding a new nullable TIMESTAMP column in schema, mysqldef will generate a DDL without specifying NULL or not and result in an error like following

```
ERROR 1067 (42000): Invalid default value for 'created_at'
```

##### Environment

- **mysqldef**: 0.5.14
- **mysql**: 5.7

##### Initial Schema

```sql
CREATE TABLE user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT 'konsumer'
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;
```

##### New Schema

```sql
CREATE TABLE user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT 'konsumer',
  created_at TIMESTAMP NULL DEFAULT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;
```

#### Current Generated DDLs

```sql
ALTER TABLE user ADD COLUMN created_at timestamp DEFAULT null AFTER name
```

#### Expected Generated DDLs

```sql
ALTER TABLE user ADD COLUMN created_at timestamp NULL DEFAULT null AFTER name
```

---

I tried to run the expected one locally and it works fine on MySQL.

**Comment by k0kubun** [comment] 2020-09-25 03:17
Thank you for your report. While I can fix sqldef's behavior to print the "Expected Generated DDLs", I couldn't reproduce your issue:

```sql
$ mysql -uroot -e 'create database test;'

$ cat /tmp/a.sql
CREATE TABLE user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT 'konsumer'
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;

$ go run cmd/mysqldef/mysqldef.go -uroot test < /tmp/a.sql
-- Apply --
CREATE TABLE user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT 'konsumer'
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;

$ cat /tmp/b.sql
CREATE TABLE user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT 'konsumer',
  created_at DATETIME NULL DEFAULT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;

$ go run cmd/mysqldef/mysqldef.go -uroot test < /tmp/b.sql
-- Apply --
ALTER TABLE user ADD COLUMN created_at datetime DEFAULT null AFTER name;
```

It feels like the column gets `NOT NULL` if `NULL` is not explicitly specified, which I believe isn't the default behavior of MySQL. 

> https://dev.mysql.com/doc/refman/5.7/en/create-table.html
> If neither NULL nor NOT NULL is specified, the column is treated as though NULL had been specified.

Is it configured explicitly in your environment as such? I'd like to know how to do that for running tests with the mode.

**Comment by CYBAI** [comment] 2020-09-28 05:13
@k0kubun  I tried to check my environment and didn't see any special settings though, I think you're right that the default behavior should be `NULL`. I will try to investigate more about my environment and see if I can provide how to test in this mode. Thanks!

**Comment by k0kubun** [comment] 2020-10-04 04:04
Let me close this issue until the investigation is done. Please feel free to reopen this issue when you finish it or you need the workaround first.

**Comment by CYBAI** [comment] 2020-10-06 03:39
@k0kubun I think I might need your help for the workaround first 🙏 

I tried to ask my colleague and confirmed following configurations in our `docker-compose.yml` 👇 

```yaml
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_bin
    - --general-log-file=/var/log/mysql/query.log
    - --general-log=true
    - --long-query-time=1
    - --slow-query-log-file=/var/log/mysql/slow.log
    - --slow-query-log=true
    environment:
    - LANG=C.UTF-8
    - MYSQL_DATABASE=${MYSQL_DATABASE}
```

I can't find any of them can have impact to the `NULL` / `NON NULL` configuration :/

**Comment by k0kubun** [comment] 2020-10-06 03:55
> I think I might need your help for the workaround first

OK.

> I can't find any of them can have impact to the NULL / NON NULL configuration :/

but you could reproduce the issue using docker-compose? If possible, I would appreciate an entire docker-compose which could reproduce the behavior (at least I need to know the Docker image name if public).

**Comment by CYBAI** [comment] 2020-10-06 04:10
> > I think I might need your help for the workaround first
> 
> OK.

Thank you!
 
> > I can't find any of them can have impact to the NULL / NON NULL configuration :/
> 
> but you could reproduce the issue using the docker-compose.yml? If possible, I would appreciate an entire docker-compose.yml which could reproduce the behavior (at least I need to know the Docker image name if public).

Unfortunately, the docker-compose.yml is in our private repo >_<

Btw, I'm using `mysql:5.7` docker image. The most interesting (or I should say weird) thing is that I can run those DDLs in https://github.com/k0kubun/sqldef/issues/63#issuecomment-698697349 with accessing into the mysql container and creating a new test database. :/

**Comment by CYBAI** [comment] 2020-10-06 04:12
oh, wait! because I'm running commands with `Makefile` in our codebase, I just checked the `Makefile` and see we set `'SET GLOBAL FOREIGN_KEY_CHECKS=0'` before running `mysqldef`.

**Comment by CYBAI** [comment] 2020-10-06 04:24
@k0kubun gotcha! I finally found we set **sql_mode** in our Haskell backend service instead of from the docker-compose.yaml :/ which it sets `NO_ZERO_DATE` and `NO_ZERO_IN_DATE`.

**Comment by k0kubun** [comment] 2020-10-06 04:32
Great, thanks! I'll try reproducing and fixing it.

**Comment by CYBAI** [comment] 2020-10-06 04:34
> Great, thanks! I'll try reproducing and fixing it.

Thank you so much!

Sorry for that I just report that too quick >_< I found I still can reproduce the error with removing the 2 configs. Let me confirm them properly and report it again! Thank you!

**Comment by k0kubun** [comment] 2020-10-06 05:02
Oh yeah, neither NO_ZERO_DATE nor NO_ZERO_IN_DATE didn't reproduce it. I tried some other strict modes but it didn't do it either. I tried to look for such other options, but I've failed to find it so far.

> Let me confirm them properly and report it again! Thank you!

Thanks, let me (close this issue for now and) wait for the report first :pray:

**Comment by CYBAI** [comment] 2020-10-06 05:04
> > Let me confirm them properly and report it again! Thank you!
> 
> Thanks, let me (close this issue for now and) wait for the report first 🙏

Thank you! I wish I can report the root cause soon!

**Comment by CYBAI** [comment] 2020-10-06 05:51
With doing some more investigation, I found I still got the invalid default value error even removing all `sql_mode` by `SET GLOBAL sql_mode = ''`. (With searching the error on the internet, most solutions say just set `sql_mode` to empty)

However, I found I can fix the issue with turning **on** `explicit_defaults_for_timestamp`.

But, I'm very confused 🤔 With reading [the documentation of `explicit_defaults_for_timestamp`](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp), it should be default in `OFF` (that my db is also default in `OFF`) so I'd expect I can reproduce the invalid default issue in any new created database but it didn't :/

I feel I don't actually find the root cause though... 😞 Though I'm able to fix the issue with setting `--explicit_defaults_for_timestamp=ON` on my side, could you please help me to see if the configuration is `OFF` in your environment? Thank you!

**Comment by k0kubun** [comment] 2020-10-06 06:21
> could you please help me to see if the configuration is OFF in your environment?

Sure, it was:

```
mysql> show variables like '%explicit%';
+---------------------------------+-------+
| Variable_name                   | Value |
+---------------------------------+-------+
| explicit_defaults_for_timestamp | OFF   |
+---------------------------------+-------+
1 row in set (0.00 sec)
```

**Comment by k0kubun** [comment] 2020-10-06 06:33
Just an additional info:

> https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp
> TIMESTAMP columns not explicitly declared with the NULL attribute are automatically declared with the NOT NULL attribute.

After seeing that, I tested `TIMESTAMP` instead of `DATETIME`:

```diff
 CREATE TABLE user (
   id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(128) DEFAULT 'konsumer',
+  created_at TIMESTAMP NULL DEFAULT NULL
 ) Engine=InnoDB DEFAULT CHARSET=utf8mb4;
```

and got an error similar to yours:

```
$ go run cmd/mysqldef/mysqldef.go -uroot test < /tmp/a.sql
-- Apply --
ALTER TABLE user ADD COLUMN created_at timestamp DEFAULT null AFTER name;
2020/10/05 23:28:27 Error 1067: Invalid default value for 'created_at'
exit status 1
```

and this doesn't happen with `DATETIME`, although I'm not sure the doc intends to also cover `DATETIME` by "`TIMESTAMP` columns" or not.

**Comment by k0kubun** [comment] 2020-10-06 06:39
At this point, I could write a failing test with the default configuration. I can implement the original proposal, because it's not really a workaround but a reasonable fix.

**Comment by CYBAI** [comment] 2020-10-06 06:48
> After seeing that, I tested `TIMESTAMP` instead of `DATETIME`:

Aaaaah!! Thanks for catching it!!!! I mis-interpret `DATETIME` as `TIMESTAMP` in my head 😭

**Comment by CYBAI** [comment] 2020-10-06 06:55
I just changed the issue name and description to match the exact issue!

**Closed** 2020-10-06 07:06 UTC

**Comment by k0kubun** [comment] 2020-10-06 07:08
Thanks to all your helps, I fixed the issue at https://github.com/k0kubun/sqldef/commit/50197f9ec77366cc6facac15379a9830bd78e75d and [started the release](https://travis-ci.org/github/k0kubun/sqldef/builds/733212793) as v0.7.2.

**Comment by CYBAI** [comment] 2020-10-06 07:10
Thank your so much as well for your patience and quick fix!
