### ISSUE TITLE
Failed on v0.10.16 due to trigger

### ISSUE THREAD

**Issue by touyu** [k0kubun/sqldef#143] opened 2021-08-23 07:10 UTC
Originally, I set `trigger` without using mysqldef.
I raised mysqldef to v0.10.16 and it was successful until now, but now it fails.
```
found syntax error when parsing DDL "CREATE TRIGGER set_logical_uniqueness_on_article_attachments BEFORE UPDATE ON article_attachments FOR EACH ROW
BEGIN
 IF NEW.deleted_at IS NULL THEN
   SET NEW.logical_uniqueness = true": syntax error at position 117 near 'begin'
```

This trigger is as follows:
```
CREATE TRIGGER set_logical_uniqueness_on_article_attachments BEFORE UPDATE ON article_attachments FOR EACH ROW
BEGIN
 IF NEW.deleted_at IS NULL THEN
   SET NEW.logical_uniqueness = true;
 ELSE
   SET NEW.logical_uniqueness = NULL;
 END IF;
END
```

I think this is probably a problem around the delimiter, is there a solution?

## Environemnt
- mysqldef(v0.10.16)

**Comment by k0kubun** [comment] 2021-08-23 07:23
We are planning to merge improvements around the trigger support at the end of this month. Please consider using an old version in the meantime.

**Comment by k0kubun** [comment] 2021-08-31 05:20
Status update: We merged all of the trigger-related pull requests, but they didn't approach this issue. I'm guessing we need to support `BEGIN` syntax for your use. Let me give me some time to look into it.

As of now, only trigger-related changes have been added since v0.10.15. So the workaround for you will continue to be using v0.10.15 for now.

**Comment by touyu** [comment] 2021-08-31 05:23
I understand. Thank you for your reply.

**Comment by k0kubun** [comment] 2021-09-28 04:12
Is this possibly a duplicate of https://github.com/k0kubun/sqldef/issues/158? I started to take a look at it from this issue, but because this issue doesn't follow the issue template unlike https://github.com/k0kubun/sqldef/issues/158, I failed to reproduce what you are trying to do. More specifically, the DDL in "This trigger is as follows" failed even with mysql(1):

```
$ mysql -uroot -h 127.0.0.1 test < /tmp/a.sql
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4
```

Let me close this issue and focus on fixing https://github.com/k0kubun/sqldef/issues/158 first. Thanks.

**Closed by k0kubun** 2021-09-28 04:12 UTC

**Comment by k0kubun** [comment] 2021-09-28 05:11
I actually noticed it's not really a duplicate. I may retry reproducing what you want with mysql(1) again, but updating your description conforming to the issue template would be always helpful.

**Comment by k0kubun** [comment] 2021-09-28 05:54
Sorry, I tried again, but I gave up. For some reason, your SQL isn't recognized as a valid SQL with a `mysql:5.7` container. Please consider filing a new issue, following the issue template. Also, information on your MySQL server version might be helpful for this issue.
